name: Build Version

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write


jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Prepare Git
        run: |
          git config --local user.email "me@marioparashiv.com"
          git config --local user.name "GitHub Actions"

      - name: Bump Patch Version
        if: ${{ !contains(github.event.head_commit.message, 'major') && !contains(github.event.head_commit.message, 'major') }}
        run: |
          pnpm version patch

      - name: Bump Minor Version
        if: contains(github.event.head_commit.message, 'patch')
        run: |
          pnpm version minor

      - name: Bump Major Version
        if: contains(github.event.head_commit.message, 'major')
        run: |
          pnpm version major

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}